spring:
  application:
    name: sysgateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
            - GET
            - POST
            - PUT
            - DELETE
      routes:            #路由
        - id : goods      #路由id,可以随便写
          uri: lb://goods  #代理的服务地址(真实地址);lb表示重注册中心中获取的服务
          predicates:         #路由断言:可以匹配映射路径
          - Path=/goods/**  #求路径
          filters:
          - StripPrefix= 1  #去除一个前缀
#          - name: RequestRateLimiter #请求数限流 名字不能随便写
#            args:
#              key-resolver: "#{@ipKeyResolver}" #用于限流的键的解析器的 Bean 对象的名字。它使用 SpEL 表达式根据#{@beanName}从 Spring 容器中获取 Bean 对象。
#              redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充平均速率
#              redis-rate-limiter.burstCapacity: 1 #令牌桶总容量

        - id: system
          uri: lb://system
          predicates:
          - Path=/system/**
          filters:
          - StripPrefix= 1

        - id: backstage     #后台页面
          uri: lb://backstage
          predicates:
          - Path=/backstage/**
          filters:
          - StripPrefix= 1
# 配置Redis 127.0.0.1可以省略配置
redis:
  host: 192.168.38.132
  port: 6379
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka
  instance:
    prefer-ip-address: true